//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dotSwitcher.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{\"KeyData\":{\"vkCode\":19,\"scanCode\":0,\"flags\":0,\"time\":0,\"dwExtraInfo\":{\"value\":0}" +
            "},\"CtrlIsPressed\":false,\"AltIsPressed\":false,\"ShiftIsPressed\":false,\"WinIsPresse" +
            "d\":false}")]
        public string convertLastShortcut {
            get {
                return ((string)(this["convertLastShortcut"]));
            }
            set {
                this["convertLastShortcut"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{\"KeyData\":{\"vkCode\":19,\"scanCode\":0,\"flags\":0,\"time\":0,\"dwExtraInfo\":{\"value\":0}" +
            "},\"CtrlIsPressed\":false,\"AltIsPressed\":false,\"ShiftIsPressed\":true,\"WinIsPressed" +
            "\":false}")]
        public string convertSelectionShortcut {
            get {
                return ((string)(this["convertSelectionShortcut"]));
            }
            set {
                this["convertSelectionShortcut"] = value;
            }
        }
    }
}
